services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: soton_therapy
    networks:
      backend-network:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017

  deno-app:
    container_name: deno-app
    hostname: deno-app
    command: deno task test-local
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env
    networks:
      backend-network:
        aliases:
          - deno-app
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3000:3000"

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data:
